version: '3'

services:
  cart-service:
    container_name: cart-service
    image: cart-service:1.0.0-SNAPSHOT
    restart: on-failure
    ports:
      - '7000:8080'
    depends_on:
      - docker-ecomm-mysql

  checkout-service:
    container_name: checkout-service
    image: checkout-service:1.0.0-SNAPSHOT
    restart: on-failure
    ports:
      - '7001:8080'
    depends_on:
      - docker-ecomm-mysql

  order-service:
    container_name: order-service
    image: order-service:1.0.0-SNAPSHOT
    restart: on-failure
    ports:
      - '7002:8080'
    depends_on:
      - docker-ecomm-mysql

  product-service:
    container_name: product-service
    image: product-service:1.0.0-SNAPSHOT
    restart: on-failure
    ports:
      - '7003:8080'
    depends_on:
      - docker-ecomm-mysql

  docker-ecomm-mysql:
    container_name: docker-ecomm-mysql
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: ecommdb
      MYSQL_ROOT_PASSWORD: abc123
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    ports:
      - 6668:3306
    healthcheck:
      test: "/usr/bin/mysql --user=root password=abc123 --execute \"SHOW DATABASES \""
      interval: 1s
      timeout: 20s
      retries: 10
